blank_issues_enabled: false
contact_links:
  - name: Questions & discussions
    url: https://github.com/inoio/agents-sandbox/discussions
    about: You might want to ask questions and discuss ideas before opening an issue