// Package configmigration migrates supported native agent credentials into the
// agents-sandbox configuration without copying raw credentials into the VM.
package configmigration

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"maps"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/titanous/json5"
	"gopkg.in/yaml.v3"

	"github.com/inoio/agents-sandbox/internal/agent"
)

const (
	authTypeWellKnown = "wellknown"
	authTypeField     = "type"
	endpointKey       = "endpoint"
	urlKey            = "url"
	providerKey       = "provider"
	secretKey         = "secret"
	baseURLKey        = "baseURL"
)

// ErrUnsupported is returned when an agent has no safe migration provider.
var ErrUnsupported = errors.New("agent does not support safe config migration")

// ErrRerunRequired reports that the user selected native host-config
// provisioning and must rerun agents-sandbox after the config change.
var ErrRerunRequired = errors.New("configuration changed; rerun agents-sandbox")

// ErrStartDeferred reports that the user chose to review generated migration
// files before starting the sandbox.
var ErrStartDeferred = errors.New("sandbox start deferred for migration review")

// Secret is a microsandbox secret definition written to env.secret.yaml.
// Values exist only in the host-side migration plan and are never included in
// generated VM files.
type Secret struct {
	Value                 string   `yaml:"value"`
	Host                  string   `yaml:"host,omitempty"`
	Hosts                 []string `yaml:"hosts,omitempty"`
	AllowAnyHostDangerous bool     `yaml:"allow_any_host_dangerous,omitempty"`
}

// File is a host-side file generated by a migration.
type File struct {
	Path string
	Data []byte
	Mode os.FileMode
}

// Plan contains all changes needed for a safe migration. It is intentionally
// host-side: applying it does not contact or modify a VM.
type Plan struct {
	AgentName         string
	Files             []File
	Secrets           map[string]Secret
	ConfigPath        string
	ConfigData        []byte
	SecretPath        string
	SourceHash        string
	HasNativeConfig   bool
	HasManagedConfig  bool
	AlreadyConfigured bool
	Handled           bool
	Dismissed         bool
	Warnings          []string
	ReviewRequired    bool
	NetworkHosts      []string
	NetworkPath       string
	NetworkData       []byte
	NetworkAllowHosts []string
	ReviewWarnings    []string
	Retrying          bool
}

// HasChanges reports whether the plan has something useful to migrate.
func (p *Plan) HasChanges() bool {
	return p != nil && p.HasNativeConfig && len(p.Files) > 0 && !p.HasManagedConfig && !p.AlreadyConfigured &&
		!p.Handled &&
		!p.Dismissed
}
func sanitizeAuth(
	data []byte,
	knownHosts, providerHosts map[string]string,
) ([]byte, map[string]Secret, []string, error) {
	spec := defaultMigrationSpec()
	return sanitizeAuthWithSpec(data, spec, knownHosts, providerHosts)
}

func sanitizeAuthWithSpec(
	data []byte,
	spec agent.ConfigMigrationSpec,
	knownHosts, providerHosts map[string]string,
) ([]byte, map[string]Secret, []string, error) {
	var providers map[string]json.RawMessage
	if err := json.Unmarshal(data, &providers); err != nil {
		return nil, nil, nil, fmt.Errorf("parse auth.json: %w", err)
	}
	result := make(map[string]json.RawMessage)
	secrets := make(map[string]Secret)
	var warnings []string
	providerNames := make([]string, 0, len(providers))
	for provider := range providers {
		providerNames = append(providerNames, provider)
	}
	sort.Strings(providerNames)
	for _, provider := range providerNames {
		auth, fields, warning := parseAuthEntry(provider, providers[provider], spec.Auth)
		if warning != "" {
			warnings = append(warnings, warning)
			continue
		}
		for _, field := range fields {
			if replaceErr := replaceAuthField(
				auth,
				provider,
				field,
				spec.Auth,
				knownHosts,
				providerHosts,
				secrets,
			); replaceErr != nil {
				return nil, nil, nil, replaceErr
			}
		}
		if err := sanitizeAuthMapWithSpec(
			auth,
			provider,
			"",
			spec.Auth,
			knownHosts,
			providerHosts,
			secrets,
		); err != nil {
			return nil, nil, nil, err
		}
		warnings = append(warnings, unsupportedAuthFieldWarnings(auth, provider, "", spec.Auth)...)
		encoded, err := marshalJSONFn(auth)
		if err != nil {
			return nil, nil, nil, fmt.Errorf("marshal auth entry %q: %w", provider, err)
		}
		result[provider] = encoded
	}
	if len(result) == 0 {
		return nil, secrets, warnings, nil
	}
	encoded, err := marshalJSONIndentFn(result, "", "  ")
	if err != nil {
		return nil, nil, nil, fmt.Errorf("marshal migrated auth: %w", err)
	}
	return append(encoded, '\n'), secrets, warnings, nil
}

//nolint:unparam // compatibility wrapper used by existing package tests
func sanitizeAuthMap(
	values map[string]json.RawMessage,
	provider, path string,
	knownHosts, providerHosts map[string]string,
	secrets map[string]Secret,
) error {
	return sanitizeAuthMapWithSpec(
		values,
		provider,
		path,
		defaultMigrationSpec().Auth,
		knownHosts,
		providerHosts,
		secrets,
	)
}

func sanitizeAuthMapWithSpec( //nolint:gocognit // recursive redaction handles nested auth metadata
	values map[string]json.RawMessage,
	provider, path string,
	spec agent.AuthMigrationSpec,
	knownHosts, providerHosts map[string]string,
	secrets map[string]Secret,
) error {
	for key, raw := range values {
		fieldPath := key
		if path != "" {
			fieldPath = path + "_" + key
		}
		var nested map[string]json.RawMessage
		if err := json.Unmarshal(raw, &nested); err == nil && nested != nil {
			if err := sanitizeAuthMapWithSpec(
				nested,
				provider,
				fieldPath,
				spec,
				knownHosts,
				providerHosts,
				secrets,
			); err != nil {
				return err
			}
			data, marshalErr := marshalJSONFn(nested)
			if marshalErr != nil {
				return marshalErr
			}
			values[key] = data
			continue
		}
		var text string
		if jsonFieldString(values, "type") == authTypeWellKnown && strings.EqualFold(key, "key") {
			continue
		}
		if err := json.Unmarshal(
			raw,
			&text,
		); err != nil ||
			isPlaceholderWithAuthSpec(text, spec) {
			continue
		}
		if spec.RejectUnresolvedValues && isUnresolvedPiConfigValue(text) {
			return fmt.Errorf(
				"auth field %s.%s contains an unresolved environment or command reference",
				provider,
				fieldPath,
			)
		}
		if !isSensitiveField(key, spec.SensitiveFields) {
			if spec.RejectUnresolvedValues && isCredentialContainerPath(path) && text != "" {
				return fmt.Errorf("auth field %s.%s contains an unsupported environment override", provider, fieldPath)
			}
			if !isSafeField(key, spec.SafeFields) {
				continue
			}
			continue
		}
		name := spec.SecretPrefix + "_" + secretPart(provider+"_"+fieldPath)
		if existing, ok := secrets[name]; ok && existing.Value != text {
			return fmt.Errorf("secret name collision for %s", name)
		}
		secrets[name] = Secret{ //nolint:exhaustruct // auth migrations only set value and inferred hosts
			Value: text,
			Hosts: authHosts(provider, values, knownHosts, providerHosts),
		}
		encoded, marshalErr := marshalJSONFn(spec.AuthPlaceholderPrefix + name)
		if marshalErr != nil {
			return marshalErr
		}
		values[key] = encoded
	}
	return nil
}

func unsupportedAuthFieldWarnings(
	values map[string]json.RawMessage,
	provider, path string,
	spec agent.AuthMigrationSpec,
) []string {
	var warnings []string
	for key, raw := range values {
		fieldPath := key
		if path != "" {
			fieldPath = path + "." + key
		}
		var nested map[string]json.RawMessage
		if err := json.Unmarshal(raw, &nested); err == nil && nested != nil {
			warnings = append(warnings, unsupportedAuthFieldWarnings(nested, provider, fieldPath, spec)...)
			continue
		}
		if key == authTypeField || isSensitiveField(key, spec.SensitiveFields) || isSafeField(key, spec.SafeFields) {
			continue
		}
		var text string
		if json.Unmarshal(raw, &text) == nil && text != "" &&
			!isPlaceholderWithAuthSpec(text, spec) {
			warnings = append(warnings, fmt.Sprintf(
				"review required: auth field %s.%s is not recognized as safe or sensitive; inspect the generated file and submit an issue if automatic migration should support it",
				provider,
				fieldPath,
			))
		}
	}
	return warnings
}

func parseAuthEntry(
	provider string,
	data json.RawMessage,
	spec agent.AuthMigrationSpec,
) (map[string]json.RawMessage, []string, string) {
	var auth map[string]json.RawMessage
	if err := json.Unmarshal(data, &auth); err != nil {
		return nil, nil, fmt.Sprintf("skipped malformed auth entry %q", provider)
	}
	var authType string
	if err := json.Unmarshal(auth["type"], &authType); err != nil {
		return nil, nil, fmt.Sprintf("skipped auth entry %q without a supported type", provider)
	}
	fields := authFieldsFor(spec, authType)
	if len(fields) == 0 {
		return nil, nil, fmt.Sprintf("skipped unsupported auth type %q for provider %q", authType, provider)
	}
	return auth, fields, ""
}

func replaceAuthField(
	auth map[string]json.RawMessage,
	provider, field string,
	spec agent.AuthMigrationSpec,
	knownHosts, providerHosts map[string]string,
	secrets map[string]Secret,
) error {
	raw, exists := auth[field]
	if !exists {
		return nil
	}
	var value string
	if err := json.Unmarshal(raw, &value); err != nil {
		return fmt.Errorf("auth field %s.%s is not a string", provider, field)
	}
	if isPlaceholderWithAuthSpec(value, spec) || value == "opencode-oauth-dummy-key" {
		return nil
	}
	if spec.RejectUnresolvedValues && isUnresolvedPiConfigValue(value) {
		return fmt.Errorf("auth field %s.%s contains an unresolved environment or command reference", provider, field)
	}
	name := spec.SecretPrefix + "_" + secretPart(provider) + "_" + strings.ToUpper(field)
	if existing, ok := secrets[name]; ok && existing.Value != value {
		return fmt.Errorf("secret name collision for %s", name)
	}
	secrets[name] = Secret{ //nolint:exhaustruct // auth migrations only set value and inferred hosts
		Value: value,
		Hosts: authHosts(provider, auth, knownHosts, providerHosts),
	}
	auth[field] = json.RawMessage(fmt.Sprintf("%q", spec.AuthPlaceholderPrefix+name))
	return nil
}

func jsonFieldString(values map[string]json.RawMessage, key string) string {
	var value string
	_ = json.Unmarshal(values[key], &value)
	return value
}

func authHosts(provider string, auth map[string]json.RawMessage, knownHosts, providerHosts map[string]string) []string {
	if provider == "github-copilot" {
		if enterprise := jsonFieldString(auth, "enterpriseUrl"); enterprise != "" {
			if parsed, err := url.Parse(enterprise); err == nil && parsed.Hostname() != "" {
				return []string{"copilot-api." + parsed.Hostname()}
			}
		}
	}
	if jsonFieldString(auth, "type") == authTypeWellKnown {
		if parsed, err := url.Parse(provider); err == nil && parsed.Hostname() != "" {
			return []string{parsed.Hostname()}
		}
	}
	if host := providerHosts[strings.ToLower(provider)]; host != "" {
		return []string{host}
	}
	return knownHost(provider, knownHosts)
}

func migrateNativeConfig(
	hostHome string,
	spec agent.ConfigMigrationSpec,
) ([]byte, map[string]Secret, []string, map[string]string, error) {
	configDir, _ := nativeAgentPaths(hostHome, spec)
	var merged map[string]any
	var warnings []string
	for _, name := range spec.NativeConfigFiles {
		data, err := os.ReadFile(filepath.Join(configDir, name))
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, nil, nil, nil, fmt.Errorf("read native config %s: %w", name, err)
		}
		parsed, parseErr := parseNativeConfig(name, data)
		if parseErr != nil {
			warnings = append(warnings, fmt.Sprintf("skipped malformed native config %q", name))
			continue
		}
		merged = mergeConfigMaps(merged, parsed)
	}
	if len(merged) == 0 {
		return nil, nil, warnings, nil, nil
	}
	secrets := make(map[string]Secret)
	providerHosts := providerEndpointHostsWithSpec(merged, spec.Auth.EndpointFields)
	if sanitizeErr := sanitizeConfigMapWithSpec(
		merged,
		"",
		"",
		spec.Auth,
		spec.KnownProviderHosts,
		providerHosts,
		secrets,
	); sanitizeErr != nil {
		return nil, nil, nil, nil, sanitizeErr
	}
	data, err := marshalJSONIndentFn(merged, "", "  ")
	if err != nil {
		return nil, nil, nil, nil, fmt.Errorf("marshal migrated agent config: %w", err)
	}
	return append(data, '\n'), secrets, warnings, providerHosts, nil
}

func migrateNativeSupplementalConfig(
	hostHome string,
	spec agent.ConfigMigrationSpec,
) (map[string][]byte, map[string]Secret, []string, map[string]string, error) {
	configDir, _ := nativeAgentPaths(hostHome, spec)
	files := make(map[string][]byte)
	secrets := make(map[string]Secret)
	var warnings []string
	providerHosts := make(map[string]string)
	for index, name := range spec.NativeSupplementalFiles {
		data, err := os.ReadFile(filepath.Join(configDir, name))
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, nil, nil, nil, fmt.Errorf("read native config %s: %w", name, err)
		}
		parsed, parseErr := parseNativeConfig(name, data)
		if parseErr != nil {
			warnings = append(warnings, fmt.Sprintf("skipped malformed native config %q", name))
			continue
		}
		fileSecrets := make(map[string]Secret)
		fileHosts := providerEndpointHostsWithSpec(parsed, spec.Auth.EndpointFields)
		if sanitizeErr := sanitizeConfigMapWithSpec(
			parsed,
			"",
			"",
			spec.Auth,
			spec.KnownProviderHosts,
			fileHosts,
			fileSecrets,
		); sanitizeErr != nil {
			return nil, nil, nil, nil, sanitizeErr
		}
		if err := mergePlannedSecrets(secrets, fileSecrets); err != nil {
			return nil, nil, nil, nil, err
		}
		maps.Copy(providerHosts, fileHosts)
		encoded, marshalErr := marshalJSONIndentFn(parsed, "", "  ")
		if marshalErr != nil {
			return nil, nil, nil, nil, fmt.Errorf("marshal migrated agent config %q: %w", name, marshalErr)
		}
		managedName := name
		if index < len(spec.ManagedSupplementalFiles) && spec.ManagedSupplementalFiles[index] != "" {
			managedName = spec.ManagedSupplementalFiles[index]
		}
		files[managedName] = append(encoded, '\n')
	}
	return files, secrets, warnings, providerHosts, nil
}

func parseNativeConfig(name string, data []byte) (map[string]any, error) {
	var result map[string]any
	switch strings.ToLower(filepath.Ext(name)) {
	case extYAML, extYML:
		if err := yaml.Unmarshal(data, &result); err != nil {
			return nil, err
		}
	default:
		if err := json5.Unmarshal(data, &result); err != nil {
			return nil, err
		}
	}
	return result, nil
}

func mergeConfigMaps(base, override map[string]any) map[string]any {
	if base == nil {
		base = make(map[string]any)
	}
	result := make(map[string]any, len(base)+len(override))
	maps.Copy(result, base)
	for key, value := range override {
		baseMap, baseOK := result[key].(map[string]any)
		overrideMap, overrideOK := value.(map[string]any)
		if baseOK && overrideOK {
			result[key] = mergeConfigMaps(baseMap, overrideMap)
		} else {
			result[key] = value
		}
	}
	return result
}

//nolint:unparam // compatibility wrapper used by existing package tests
func sanitizeConfigMap(
	values map[string]any,
	provider string,
	path string,
	knownHosts, providerHosts map[string]string,
	secrets map[string]Secret,
) error {
	return sanitizeConfigMapWithSpec(
		values,
		provider,
		path,
		defaultMigrationSpec().Auth,
		knownHosts,
		providerHosts,
		secrets,
	)
}

//nolint:gocognit // recursive traversal keeps redaction and path context together
func sanitizeConfigMapWithSpec(
	values map[string]any,
	provider string,
	path string,
	spec agent.AuthMigrationSpec,
	knownHosts, providerHosts map[string]string,
	secrets map[string]Secret,
) error {
	for key, value := range values {
		currentPath := key
		if path != "" {
			currentPath = path + "_" + key
		}
		if nested, ok := value.(map[string]any); ok {
			nestedProvider := provider
			if path == "" && (key == providerKey || key == "providers") {
				nestedProvider = ""
			}
			if path == providerKey || path == "providers" {
				nestedProvider = key
			}
			if err := sanitizeConfigMapWithSpec(
				nested,
				nestedProvider,
				currentPath,
				spec,
				knownHosts,
				providerHosts,
				secrets,
			); err != nil {
				return err
			}
			continue
		}
		if array, ok := value.([]any); ok {
			for index, item := range array {
				if nested, nestedOK := item.(map[string]any); nestedOK {
					if err := sanitizeConfigMapWithSpec(
						nested,
						provider,
						fmt.Sprintf("%s_%d", currentPath, index),
						spec,
						knownHosts,
						providerHosts,
						secrets,
					); err != nil {
						return err
					}
				}
			}
			continue
		}
		text, ok := value.(string)
		if ok && spec.RejectUnresolvedValues && isUnresolvedPiConfigValue(text) {
			return fmt.Errorf("config field %s contains an unresolved environment or command reference", currentPath)
		}
		if ok && spec.RejectUnresolvedValues && isCredentialContainerPath(path) &&
			!isPlaceholderWithAuthSpec(text, spec) {
			return fmt.Errorf("config field %s contains an unsupported credential or header override", currentPath)
		}
		if !ok || !isSensitiveField(key, spec.ConfigSensitiveFields) ||
			isPlaceholderWithAuthSpec(text, spec) {
			if ok && isEndpointField(key, spec.EndpointFields) {
				if err := rejectEmbeddedEndpointCredential(text); err != nil {
					return fmt.Errorf("config field %s: %w", currentPath, err)
				}
			}
			continue
		}
		name := spec.SecretPrefix + "_CONFIG_" + secretPart(currentPath)
		if existing, exists := secrets[name]; exists && existing.Value != text {
			name += "_" + shortHash(text)
		}
		secrets[name] = Secret{ //nolint:exhaustruct // config migrations only set value and inferred hosts
			Value: text,
			Hosts: configSecretHosts(provider, values, knownHosts, providerHosts),
		}
		values[key] = spec.ConfigPlaceholderPrefix + name + spec.ConfigPlaceholderSuffix
	}
	return nil
}

func isCredentialContainerPath(path string) bool {
	normalized := strings.ToLower(path)
	return normalized == "env" || strings.HasSuffix(normalized, "_env") ||
		normalized == "headers" || strings.HasSuffix(normalized, "_headers")
}

func isSensitiveConfigKey(key string) bool {
	normalized := strings.ToLower(strings.Map(func(r rune) rune {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			return r
		}
		return -1
	}, key))
	switch normalized {
	case "apikey", "xapikey", "apitoken", "authtoken", "accesstoken", "refreshtoken", "idtoken",
		"bearertoken", "sessiontoken", "oauthtoken", "oauthaccess", "oauthrefresh", secretKey, "clientsecret",
		"secretaccesskey", "privatekey", "password", "authorization", "proxyauthorization", "credential", "credentials":
		return true
	default:
		return false
	}
}

func isPlaceholder(value string) bool {
	return strings.Contains(value, "$MSB_") || strings.Contains(value, "{env:") || strings.Contains(value, "{file:")
}

func configSecretHosts(provider string, values map[string]any, knownHosts, providerHosts map[string]string) []string {
	for _, key := range []string{baseURLKey, "baseUrl", endpointKey, urlKey, "enterpriseUrl"} {
		if raw, ok := values[key].(string); ok {
			if parsed, err := url.Parse(raw); err == nil && parsed.Hostname() != "" {
				return []string{parsed.Hostname()}
			}
		}
	}
	if host := knownHosts[strings.ToLower(provider)]; host != "" {
		return []string{host}
	}
	if host := providerHosts[strings.ToLower(provider)]; host != "" {
		return []string{host}
	}
	return nil
}

func providerEndpointHosts(values map[string]any) map[string]string {
	return providerEndpointHostsWithSpec(values, defaultMigrationSpec().Auth.EndpointFields)
}

func providerEndpointHostsWithSpec(values map[string]any, endpointFields []string) map[string]string {
	result := make(map[string]string)
	providers, ok := values["provider"].(map[string]any)
	if !ok {
		providers, ok = values["providers"].(map[string]any)
	}
	if !ok {
		return result
	}
	for provider, raw := range providers {
		config, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		options, _ := config["options"].(map[string]any)
		for _, key := range endpointFields {
			endpoint, endpointOK := config[key].(string)
			if !endpointOK && options != nil {
				endpoint, endpointOK = options[key].(string)
			}
			if endpointOK {
				if parsed, err := url.Parse(endpoint); err == nil && parsed.Hostname() != "" {
					result[strings.ToLower(provider)] = parsed.Hostname()
					break
				}
			}
		}
	}
	return result
}

func isEndpointKey(key string) bool {
	return isEndpointField(key, defaultMigrationSpec().Auth.EndpointFields)
}

func isEndpointField(key string, endpointFields []string) bool {
	switch strings.ToLower(key) {
	case "baseurl", endpointKey, urlKey, "enterpriseurl":
		for _, field := range endpointFields {
			if strings.EqualFold(key, field) {
				return true
			}
		}
	}
	return false
}

func rejectEmbeddedEndpointCredential(value string) error {
	parsed, err := url.Parse(value)
	if err != nil {
		return errors.New("invalid endpoint URL")
	}
	if parsed.User != nil {
		return errors.New("endpoint contains URL credentials")
	}
	for key := range parsed.Query() {
		switch strings.ToLower(strings.ReplaceAll(key, "-", "_")) {
		case "api_key", "apikey", "key", "token", "access_token", "signature", "sig", "password", secretKey:
			return errors.New("endpoint contains credential query parameters")
		}
	}
	return nil
}

func shortHash(value string) string {
	hash := sha256.Sum256([]byte(value))
	return hex.EncodeToString(hash[:])[:8]
}

func mergePlannedSecrets(base, additions map[string]Secret) error {
	for name, secret := range additions {
		if existing, ok := base[name]; ok && existing.Value != secret.Value {
			return fmt.Errorf("secret name collision for %s", name)
		}
		base[name] = secret
	}
	return nil
}

func authFields(authType string) []string {
	switch authType {
	case "oauth":
		return []string{"access", "refresh"}
	case "api":
		return []string{"key"}
	case authTypeWellKnown:
		return []string{"token"}
	default:
		return nil
	}
}

func authFieldsFor(spec agent.AuthMigrationSpec, authType string) []string {
	if fields := spec.AuthFields[authType]; len(fields) > 0 {
		return fields
	}
	return authFields(authType)
}

func isSensitiveField(key string, fields []string) bool {
	normalized := strings.ToLower(strings.Map(func(r rune) rune {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			return r
		}
		return -1
	}, key))
	for _, field := range fields {
		if normalized == strings.ToLower(strings.Map(func(r rune) rune {
			if unicode.IsLetter(r) || unicode.IsDigit(r) {
				return r
			}
			return -1
		}, field)) {
			return true
		}
	}
	return false
}

func isSafeField(key string, fields []string) bool {
	normalized := strings.ToLower(strings.Map(func(r rune) rune {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			return r
		}
		return -1
	}, key))
	for _, field := range fields {
		if normalized == strings.ToLower(field) {
			return true
		}
	}
	return false
}

func isPlaceholderWithSpec(value string, spec agent.ConfigMigrationSpec) bool {
	return strings.Contains(value, spec.Auth.AuthPlaceholderPrefix) ||
		strings.Contains(value, spec.Auth.ConfigPlaceholderPrefix)
}

func isPlaceholderWithAuthSpec(value string, spec agent.AuthMigrationSpec) bool {
	return strings.Contains(value, spec.AuthPlaceholderPrefix) || strings.Contains(value, spec.ConfigPlaceholderPrefix)
}

func isUnresolvedPiConfigValue(value string) bool {
	return strings.HasPrefix(value, "!") ||
		(strings.HasPrefix(value, "$") && !strings.HasPrefix(value, "$MSB_"))
}

func defaultMigrationSpec() agent.ConfigMigrationSpec {
	spec, ok := migrationSpecProviderFn()
	if ok {
		return spec
	}
	return agent.ConfigMigrationSpec{Auth: agent.AuthMigrationSpec{ //nolint:exhaustruct // test fallback
		SecretPrefix:            "OPENCODE",
		AuthPlaceholderPrefix:   "$MSB_",
		ConfigPlaceholderPrefix: "{env:",
	}}
}

//nolint:gochecknoglobals // package-local test seam for unsupported registries
var migrationSpecProviderFn = func() (agent.ConfigMigrationSpec, bool) {
	return lookupMigrationSpec(agent.Lookup)
}

func lookupMigrationSpec(lookup func(string) (agent.Agent, bool)) (agent.ConfigMigrationSpec, bool) {
	a, ok := lookup("opencode")
	if !ok {
		return agent.ConfigMigrationSpec{}, false
	}
	provider, ok := agent.AsMigrationSpecProvider(a)
	if !ok {
		return agent.ConfigMigrationSpec{}, false
	}
	return provider.MigrationSpec(), true
}

func secretPart(value string) string {
	var b strings.Builder
	lastUnderscore := false
	for _, r := range strings.ToUpper(value) {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
			lastUnderscore = false
		} else if !lastUnderscore {
			b.WriteByte('_')
			lastUnderscore = true
		}
	}
	return strings.Trim(b.String(), "_")
}

func knownHost(provider string, knownHosts map[string]string) []string {
	host := knownHosts[strings.ToLower(provider)]
	if host == "" {
		return nil
	}
	return []string{host}
}

func cloneSecrets(input map[string]Secret) map[string]Secret {
	result := make(map[string]Secret, len(input))
	for name, secret := range input {
		secret.Hosts = append([]string(nil), secret.Hosts...)
		result[name] = secret
	}
	return result
}

func buildLauncherConfig(a agent.Agent, spec agent.ConfigMigrationSpec) (string, []byte, error) {
	path, data, err := migrationLoadLauncherConfig()
	if err != nil {
		return "", nil, err
	}
	var root map[string]any
	if migrationIsJSONConfig(path) {
		if unmarshalErr := json5.Unmarshal(data, &root); unmarshalErr != nil {
			return "", nil, fmt.Errorf("parse launcher config %s: %w", path, unmarshalErr)
		}
	} else if unmarshalErr := yaml.Unmarshal(data, &root); unmarshalErr != nil {
		return "", nil, fmt.Errorf("parse launcher config %s: %w", path, unmarshalErr)
	}
	if root == nil {
		root = make(map[string]any)
	}
	home, ok := root["home"].(map[string]any)
	if !ok {
		home = make(map[string]any)
		root["home"] = home
	}
	mappings := make(map[string]string)
	if spec.CredentialTarget != "" && spec.ManagedCredential != "" {
		mappings[spec.CredentialTarget] = filepath.Join(a.ConfigDirName(), spec.ManagedCredential)
	}
	for _, name := range spec.ManagedSupplementalFiles {
		mappings[filepath.Join(filepath.Dir(spec.CredentialTarget), name)] = filepath.Join(a.ConfigDirName(), name)
	}
	changed := false
	for target, source := range mappings {
		if existing, ok := migrationHomeMapping(root, target); ok {
			if existing != source {
				return "", nil, fmt.Errorf("home mapping %q already points to %q", target, existing)
			}
			continue
		}
		home[target] = source
		changed = true
	}
	if !changed {
		return path, nil, nil
	}
	var updated []byte
	if migrationIsJSONConfig(path) {
		updated, err = marshalJSONIndentFn(root, "", "  ")
		updated = append(updated, '\n')
	} else {
		updated, err = marshalYAMLFn(root)
	}
	if err != nil {
		return "", nil, fmt.Errorf("marshal launcher config: %w", err)
	}
	return path, updated, nil
}
